# Site settings
title: Emmia's RPG Notes
email: contact@emmiasilk.com
description: >-
  Emmia's notes for anything RPG-related.
baseurl: ""
url: "rpgnote.emmiasilk.com"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

collections_dir: _collections
collections:
  uatera_ancestries:
    output: true
    permalink: /uatera/ancestry/:path/

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
